using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace TP_6___Huffman
{
	/**
	*** /!\ DO NOT EDIT THIS FILE /!\
	**/
    class Misc
    {
        public class TFrequency
        {
            private int[] _frequency = new int[255];

            public TFrequency()
            {
                for (int i = 0; i < 255; ++i)
                    this._frequency[i] = 0;
            }
            public int this[int i]
            {
                get { return _frequency[i]; }
                set { this._frequency[i] = value; }
            }
        }

        public class TMatch
        {
            private string[] _match = new string[255];

            public TMatch()
            {
                for (int i = 0; i < 255; ++i)
                    this._match[i] = "";
            }
            public string this[int i]
            {
                get { return _match[i]; }
                set { this._match[i] = value; }
            }
        }

        public class TBinaryTree
        {
            private char _key = '\0';
            private TBinaryTree _left = null;
            private TBinaryTree _right = null;

            public char Key
            {
                get { return _key; }
                set { _key = value; }
            }
            public TBinaryTree Left
            {
                get { return _left; }
                set { _left = value; }
            }
            public TBinaryTree Right
            {
                get { return _right; }
                set { _right = value; }
            }
        }

        public class TList
        {
            private int _weight;
            private TBinaryTree _tree = null;
            private TList _next = null;

            public int Weight
            {
                get { return _weight; }
                set { _weight = value; }
            }
            public TBinaryTree Tree
            {
                get { return _tree; }
                set { _tree = value; }
            }
            public TList Next
            {
                get { return _next; }
                set { _next = value; }
            }
        }
    }
}
